### ISSUE TITLE
TestG0StackOverflow timeout on windows/amd64 in CI

### ISSUE THREAD

**Issue by dagood** [microsoft/go#1083]
* Upstream issue for the same test having issues on windows/arm64:  
  https://github.com/golang/go/issues/63938

Lately in microsoft/main CI, a random set of Windows jobs is sometimes specifically bad at `TestG0StackOverflow` and some other runtime tests, and fails multiple retries within the same job:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=466102&view=results

> Attempt 1:
> ```
> go tool dist: FAILED
> skipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier errorskipped due to earlier error
> === Failed
> === FAIL: runtime:cpu124 TestG0StackOverflow (517.40s)
> === FAIL: runtime:cpu124 TestWERDialogue (0.08s)
> === FAIL: runtime:cpu124 TestCgoTracebackContext (unknown)
> === FAIL: runtime:cpu124 TestReturnAfterStackGrowInCallback (unknown)
> === FAIL: runtime:cpu124 TestCgoCallbackGC (unknown)
> === FAIL: runtime:cpu124 TestCgoExternalThreadPanic (unknown)
> === FAIL: runtime:cpu124 TestMemmoveOverlapLarge0x120000 (unknown)
> === FAIL: runtime:cpu124 TestConcurrentReadsAfterGrowth (unknown)
> ...
> ```
> 
> Attempt 2:
> ```
> === Failed
> === FAIL: runtime TestG0StackOverflow (950.45s)
> 
> === Errors
> go tool dist: Failed: exit status 1
> ```
> 
> Attempt 3:
> ```
> === Failed
> === FAIL: runtime:cpu124 TestG0StackOverflow (470.36s)
> === FAIL: runtime:cpu124 TestG0StackOverflow (0.00s)
> === FAIL: runtime:cpu124 TestCgoCheckBytes (unknown)
> === FAIL: runtime:cpu124 TestCgoPprofThread (unknown)
> ...
> ```
> 
> Then, job timeout.

Retrying the whole pipeline sometimes makes it succeed, sometimes not. (Might correspond to randomly getting a particular host?)

I'm not able to repro on my local machine.

**Comment by gdams** [comment]
not seen for a while
