### ISSUE TITLE
Add Windows 2019 test builders to CI

### ISSUE THREAD

**Issue by dagood** [microsoft/go#1085]
We should check that Windows 2019 works with some known MinGW builds to help with issues like this:

* https://github.com/microsoft/go/issues/1081

We should document what combination(s) we're testing, which we recommend, and how to get them.

Ideally we should also provide a script/command to check which MinGW version is actually being used, to diagnose in CI and locally without guesswork. I imagine I'll be making a tool to run in our CI to download several known versions of MinGW, so perhaps that could be shared to also use in CI to avoid depending on whatever the image provider includes.

**Comment by gdams** [comment]
Windows Server 2019 has reached EOL on January 9th. We will add 2025 builders to the CI once they become EA
