### ISSUE TITLE
Investigate go1.22rc1 SetFileInformationByHandle issue: "Invalid access to memory location"

### ISSUE THREAD

**Issue by dagood** [microsoft/go#1100]
https://github.com/moby/moby/pull/46982#issuecomment-1875350509

> The bad news; looks like Windows is pretty much broken;
> 
> ```
> failed to register layer: re-exec error: exit status 1: output: SetFileInformationByHandle \\?\C:\Windows\SystemTemp\hcs2001018820\Files.$wcidirs$: Invalid access to memory location.
> Error: Process completed with exit code 1.
> ```
> 
> That codepath seems to be hit by `go-winio`;
> 
> https://github.com/moby/moby/blob/7ad5396f79e107d9e0f1e26aa6684289c37a0e9c/vendor/github.com/Microsoft/go-winio/fileinfo.go#L21-L34
> 
> And used by hcsshim;
> 
> ```shell
> git grep '\.SetFileBasicInfo'
> vendor/github.com/Microsoft/hcsshim/internal/safefile/safeopen.go:      return winio.SetFileBasicInfo(f, &sbi)
> vendor/github.com/Microsoft/hcsshim/internal/wclayer/baselayerwriter.go:                err = winio.SetFileBasicInfo(f, &di.fileInfo)
> vendor/github.com/Microsoft/hcsshim/internal/wclayer/baselayerwriter.go:        err = winio.SetFileBasicInfo(f, fileInfo)
> vendor/github.com/Microsoft/hcsshim/internal/wclayer/legacy.go: err = winio.SetFileBasicInfo(dest, fileInfo)
> vendor/github.com/Microsoft/hcsshim/internal/wclayer/legacy.go:         err = winio.SetFileBasicInfo(f, fileInfo)
> vendor/github.com/Microsoft/hcsshim/internal/wclayer/legacy.go: err = winio.SetFileBasicInfo(f, &strippedFi)
> ```

**Comment by qmuntal** [comment]
Probably related to https://go-review.googlesource.com/c/go/+/549256.

**Comment by thaJeztah** [comment]
Thanks for looking into this! And sorry for (ab)using my "backchannels" for this. I'm not running on Windows myself, and noticed the issue when testing 1.22, and thought it might be faster for someone with more insight into Windows to triage if it’s an actual regression in Go, or if it was an existing issue in hcsshim or go-winio.

**Comment by dagood** [comment]
No problem. I've poked around and haven't been able to repro locally yet (Windows 11 or Windows Server 2019). I haven't spotted anything particularly odd about the `SetFileBasicInfo` calls or `FileBasicInfo` struct vendored in the repo, either. I'd like to run the tests directly to see what call is actually causing this, but moby/moby (and hcsshim for that matter) is a little intimidating, so I'm still working up to that.

A big difference between my local attempt and the failure is going to be the type of file handle being used. https://github.com/microsoft/hcsshim/blob/f92b8fb9c92e17da496af5a69e3ee13fbe9916e1/internal/safefile/safeopen.go#L139-L162 is pretty interesting. But, I'm not sure how that would cause this failure, and it doesn't seem like it could be related to https://go-review.googlesource.com/c/go/+/549256. (And I haven't seen anything else that seems related yet.)

**Comment by thaJeztah** [comment]
Yes, not gonna lie; running all Moby integration tests locally is not "fun" (and not something I usually do), and narrowing it down to a "small" reproducer could be challenging because of all the complexity involved.

That said; always feel free to open a draft PR in our repository if you want to try out patches / debug (and have GitHub actions run the tests).

We also have a maintainers call later Today, and I'll ask if there's people that may have ideas.

Next step for me will be to also open a draft PR in containerd to see if it has similar issues (but that may not be the case, as it's using different parts of hcsshim if it's related to how moby uses things)

**Comment by dagood** [comment]
Yeah, realized just running the action is probably the way to go, and tried it out on my own fork to start with: https://github.com/dagood/moby/pull/1.

So far, it successfully repro'd with your commit (and it did appear to re-run!). I culled the workflows and made a change to the vendored go-winio to try to get more context, but that passed. I removed the go-winio change to see if it fails again, or if culling the workflows is what made it work.

I'm also thinking I'll poke through the versions involved in the runner to try to see if this is just the result of some floating dependency.

**Comment by dagood** [comment]
I got this stack trace:

```
runtime/debug.Stack()
	C:/go/src/runtime/debug/stack.go:24 +0x5e
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.SetFileBasicInfo(0xc00007d600, 0xf?)
	C:/gopath/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/fileinfo.go:49 +0x85
github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/wclayer.(*legacyLayerWriter).Add(0xc0004448f0, {0xc0004[42](https://github.com/dagood/moby/actions/runs/7414601797/job/20176251527?pr=1#step:12:43)ae0, 0x5}, 0xc0004a1290)
	C:/gopath/src/github.com/docker/docker/vendor/github.com/Microsoft/hcsshim/internal/wclayer/legacy.go:697 +0xb54
github.com/docker/docker/daemon/graphdriver/windows.writeLayerFromTar({0x2f60e40, 0xc00007c058}, {0x2f8e120, 0xc0003dba90}, {0xc00097c[48](https://github.com/dagood/moby/actions/runs/7414601797/job/20176251527?pr=1#step:12:49)0, 0x80})
	C:/gopath/src/github.com/docker/docker/daemon/graphdriver/windows/windows.go:7[54](https://github.com/dagood/moby/actions/runs/7414601797/job/20176251527?pr=1#step:12:55) +0x312
github.com/docker/docker/daemon/graphdriver/windows.writeLayer({0x2f60e40, 0xc00007c058}, {0xc00004aa00, 0x3f}, {0xc00004aa80, 0x40}, {0xc0000920b0, 0x1, 0x1})
	C:/gopath/src/github.com/docker/docker/daemon/graphdriver/windows/windows.go:831 +0x2aa
github.com/docker/docker/daemon/graphdriver/windows.writeLayerReexec()
	C:/gopath/src/github.com/docker/docker/daemon/graphdriver/windows/windows.go:792 +0x75
github.com/docker/docker/pkg/reexec.Init(...)
	C:/gopath/src/github.com/docker/docker/pkg/reexec/reexec.go:30
main.main()
	C:/gopath/src/github.com/docker/docker/cmd/dockerd/docker.go:75 +0x196
```

It *seems* that my debug change caused it to work because it was keeping `bi` alive. This diff makes CI go from success to failure:

```diff
func SetFileBasicInfo(f *os.File, bi *FileBasicInfo) error {
	if err := windows.SetFileInformationByHandle(
		windows.Handle(f.Fd()),
		windows.FileBasicInfo,
		(*byte)(unsafe.Pointer(bi)),
		uint32(unsafe.Sizeof(*bi)),
	); err != nil {
		return &os.PathError{
			Op:   "SetFileInformationByHandle",
			Path: f.Name(),
-			Err:  fmt.Errorf("%v\n%#v\n%#v\n\n%w", string(debug.Stack()), f, bi, err),
+			Err:  fmt.Errorf("%v\n%#v\n%w", string(debug.Stack()), f, err),
		}
	}
	runtime.KeepAlive(f)
	return nil
}
```

However, after that change, I tried adding `runtime.KeepAlive(bi)` after `runtime.KeepAlive(f)`, and that *doesn't* make it work.

I'm still not able to repro something like this locally. However, I don't think I've ever triggered this type of error locally, so I might just not know how to do it effectively. 😕 

---

Something interesting is that https://go-review.googlesource.com/c/go/+/549256 makes this `internal/syscall/windows` change:

```diff
- //sys	SetFileInformationByHandle(... buf uintptr, bufsize uint32) ...
+ //sys	SetFileInformationByHandle(... buf unsafe.Pointer, bufsize uint32) ...
```

But this code uses `x/sys/windows`:

```go
//sys	SetFileInformationByHandle(... inBuffer *byte, inBufferLen uint32) ...
```

It seems like it would be too much of a coincidence for these issues to not be related in some way, though.

**Comment by dagood** [comment]
Another unintentional "fix" was to try writing a string early to pass down with the error later:

```diff
func SetFileBasicInfo(f *os.File, bi *FileBasicInfo) error {
+	s := fmt.Sprintf("%#v", bi)
	if err := windows.SetFileInformationByHandle(
---
		return &os.PathError{
			Op:   "SetFileInformationByHandle",
			Path: f.Name(),
-			Err:  fmt.Errorf("%v\n%#v\n%w", string(debug.Stack()), f, err),
+			Err:  fmt.Errorf("%v\n%v\n%#v\n%w", string(debug.Stack()), f, s, err),
		}
```

I suspect we're seeing a more random issue (race condition, corruption, uninitialized memory, etc) and none of what I'm doing is meaningful--I'm just bumping it a little. Making the workflow publish the built binary and inspecting the assembly to actually see how the compilation differs from these small changes is probably the next thing to do.

---

I tried and failed to get a more direct repro by adding a main package essentially reuses the code and libraries that hcsshim uses. I got an unrelated-seeming `Access is denied` error in `safefile.OpenRelative` when I ran it in a tight loop, but nothing like the original issue, and it's not specific to go1.22rc1. https://github.com/dagood/moby/commit/d5cb7e76f3073ba52144ea2fdb657999140a7bcf

**Comment by thaJeztah** [comment]
Just in case any of this is helpful (I realise it's pretty random);

I just stumbled upon an undocumented `DOCKER_WINDOWSFILTER_NOREEXEC` env-var that was added by the original team at Microsoft working on Windows support in Docker; they added that env-var to assist in debugging, as the "re-exec" used by the docker daemon was complicating that;

- https://github.com/moby/moby/pull/28002

I also noticed that there's PR in containerd and hcsshim that link to that PR;

- https://github.com/containerd/containerd/pull/8254
- https://github.com/microsoft/hcsshim/pull/1694

**Comment by dagood** [comment]
Hmm, that does look suspicious and could help with reproing it locally. There is a lot of other repro setup to wade through before it seems to me like that env tweak will matters, though.

I think that because tiny tweaks to this func are affecting the repro behavior, a simple explanation is that some data is being freed by Go when it shouldn't, and this all started with go1.22rc1, we should actually file an upstream issue to golang/go. Even if the problem is with the moby/moby code, getting input from the folks who truly know how the compiler works at this low level will help point in the right direction.

@thaJeztah, do you mind filing that? I could also file it with a summary of the experiments I've tried so far, if that sounds better to you.

A really unfortunate thing is that the repro isn't readily available. 😕 I haven't tried to upload an artifact with Actions yet, hopefully it's as easy as it looks. I'll be trying that next.

**Comment by thaJeztah** [comment]
Yes, I think opening a ticket in upstream would be a good thing to do, at least to put it on their radar, and maybe they have ideas.

I'm just in a call; if you have time, please go ahead and open a ticket 🤗

**Comment by dagood** [comment]
I opened https://github.com/golang/go/issues/65069, and I noticed that the binaries were already being uploaded, I just didn't know where to look for them. 😄 I posted some info about them on the issue (objdumps) and will post any future updates there.

**Comment by dagood** [comment]
@qmuntal found in https://github.com/golang/go/issues/65069 (and I confirmed on my fork) that this is an issue with the memory alignment of go-winio's FileBasicInfo. I don't see an existing issue for it, so I'll file one.

**Comment by thaJeztah** [comment]
Oh! Just catching up; interesting! At least that means we can already fix this in preparation of the Go release, correct?

ISTR there's linters for alignment in golang-ci-lint (but don't recall which one; could be an option on one of the multi-linters); of course not sure if they are suitable for this.

**Comment by dagood** [comment]
Yep, nothing's changing in the Go compiler, all that's needed is a go-winio change. (Not that it's necessarily trivial to pull that thread through the dependencies.) I submitted a PR at https://github.com/microsoft/go-winio/pull/312.

**Comment by dagood** [comment]
> ISTR there's linters for alignment in golang-ci-lint (but don't recall which one; could be an option on one of the multi-linters); of course not sure if they are suitable for this.

go-winio actually has that disabled in its config. 😄 I think that's to make sure alignment is efficient, not to make it match something that already exists.

**Comment by dagood** [comment]
https://github.com/microsoft/go-winio/pull/312 is merged and I believe that means https://github.com/moby/moby/pull/46982 is unblocked: closing our tracking issue.
