### ISSUE TITLE
Fix patches after "crypto: rollback BoringCrypto fips-20220613 update"

### ISSUE THREAD

**Issue by dagood** [microsoft/go#1119]
Once this goes into upstream:

* https://github.com/golang/go/issues/65321

We'll probably hit patch or test conflicts in microsoft/main and 1.22, 1.21, and 1.20. Essentially, we need to revert parts of:

* https://github.com/microsoft/go/pull/1097
* https://github.com/microsoft/go/pull/1110
* https://github.com/microsoft/go/pull/1104
* https://github.com/microsoft/go/pull/1103

Once the cherry-picks go through to the release branches, we should proactively merge to latest to get past the conflict, so the next release can go smoothly on each branch.

**Comment by gdams** [comment]
Quim says this is done
