### ISSUE TITLE
Go 1.22.2 binary release contains an unpatched version of Go 1.22.1

### ISSUE THREAD

**Issue by etodd** [microsoft/go#1208]
Download this file, clearly named 1.22.2: https://dotnetbuildoutput.blob.core.windows.net/golang/microsoft/release-branch.go1.22/20240403.7/go1.22.2-20240403.7.windows-amd64.zip

It seems to contain an unpatched go1.22.1 binary:
```
C:\Users\Administrator\Downloads\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe version
go version go1.22.1 windows/amd64

set GOEXPERIMENT=cngcrypto

C:\Users\Administrator\Downloads\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe version
go: unknown GOEXPERIMENT cngcrypto
```

**Comment by etodd** [comment]
The same seems to be true for this link: https://dotnetbuildoutput.blob.core.windows.net/golang/microsoft/release-branch.go1.21/20240403.5/go.20240403.5.windows-amd64.zip

**Comment by etodd** [comment]
This is the latest good build I can find: https://dotnetbuildoutput.blob.core.windows.net/golang/microsoft/release-branch.go1.22/20240320.6/go1.22.1-20240320.6.windows-amd64.zip

**Comment by dagood** [comment]
Hi, I'm not able to reproduce your result, with these files (according to pwsh `Get-FileHash`):

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          6D059CB6BE79673EC82D44DD48FA3AFC3CD4DC20473BCB8AB8BD3A98A4771696       C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64.zip
SHA256          19FCDC24DDAFF92AD5F39E0824F175A8E36B76B036A90F5496EE4D1AB60AE659       C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe
```

I get the correct version:

```
$ C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe version
go version go1.22.2 windows/amd64
```

I have Go 1.22.0 as my global install, and I'm able to use that global install to inspect the version information embedded in the downloaded go.exe and I also see the correct version number that way:

```
$ go version
go version go1.22.0 windows/amd64

$ go version C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe
C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe: go1.22.2
```

Can you show the result of `C:\Users\Administrator\Downloads\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe env`? This is mine, currently:

```
$ C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64\go\bin\go.exe env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\dagood\AppData\Local\go-build
set GOENV=C:\Users\dagood\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\dagood\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\dagood\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=local
set GOTOOLDIR=C:\tools\microsoft-go\go1.22.2-20240403.7.windows-amd64\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\dagood\AppData\Local\Temp\go-build2037830986=/tmp/go-build -gno-record-gcc-switches
```

My guess is that somehow your global install (or some other install) is being called instead of the downloaded one, but an exact mechanism that could cause that isn't coming to mind.

**Comment by etodd** [comment]
Aha!

Turns out I had previously used this command to instruct Go to auto-upgrade itself:
```
go env -w GOTOOLCHAIN=go1.22.1+auto
```

I didn't realize that once this command is run, all Go binaries of any version will redirect themselves to the binary specified by `GOTOOLCHAIN`, which is downloaded and stored in `%USERPROFILE%/go`.

The fix for me was this:
```
go env -u GOTOOLCHAIN
```

Thanks for your patience!

**Comment by dagood** [comment]
No problem! Thanks for the details about what was going on. 🙂 Our toolset changes the default from GOTOOLCHAIN=auto to GOTOOLCHAIN=local to avoid other ways of this happening, but I didn't consider it being manually overridden.
