### ISSUE TITLE
Building app with Go 1.23 OpenSSL backend emits a build warning

### ISSUE THREAD

**Issue by dagood** [microsoft/go#1305]
When I use `mcr.microsoft.com/oss/go/microsoft/golang:1.23-fips-cbl-mariner2.0` to build a simple app targeting linux-amd64 I get this output:

```
# vendor/github.com/golang-fips/openssl/v2
thread_setup_unix.c: In function 'thread_id':
thread_setup_unix.c:32:12: warning: 'pthread_setspecific' expecting 1 byte in a region of size 0 [-Wstringop-overread]
   32 |     (void) pthread_setspecific(destructor_key, (void*)1);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thread_setup_unix.c:5:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include-fixed/pthread.h:1317:12: note: in a call to function 'pthread_setspecific' declared with attribute 'access (none, 2)'
 1317 | extern int pthread_setspecific (pthread_key_t __key,
      |            ^~~~~~~~~~~~~~~~~~~
```

Dockerfile repro: https://github.com/dagood/msftgoex/blob/dev/dagood/1.23-warn/sum/Dockerfile

Repeating the repro with `mcr.microsoft.com/oss/go/microsoft/golang:1.22-fips-cbl-mariner2.0` does not emit the warning.

Note: the build succeeds.

**Comment by dagood** [comment]
`1.23-fips-bookworm` and `1.23-fips-azurelinux3.0` **don't** emit the warning. So far I've only seen `1.23-fips-cbl-mariner2.0` (and equivalent tags) emit it.

**Comment by qmuntal** [comment]
> 1.23-fips-bookworm and 1.23-fips-azurelinux3.0 don't emit the warning. So far I've only seen 1.23-fips-cbl-mariner2.0 (and equivalent tags) emit it.

This is libc version dependent. See https://github.com/golang-fips/openssl/pull/162 for a complete explanation.
