### ISSUE TITLE
Why is Ed25519 GenerateKey hard to use?

### ISSUE THREAD

**Issue by xnox** [microsoft/go#1395]
The initial crypto backend patach

https://github.com/microsoft/go/blob/23b8689cd1c5babf07943430d5d55a63e8b1dd82/patches/0002-Add-crypto-backend-foundation.patch#L319

Has

```
import cryptorand "crypto/rand"
import boring "crypto/internal/backend"
...
func GenerateKey(rand io.Reader) (PublicKey, PrivateKey,
 error) {
        if rand == nil {
                rand = cryptorand.Reader
        }
+       if boring.Enabled && boring.SupportsEd25519() {
+               if rand == boring.RandReader {
+                       priv, err := boring.GenerateKeyEd25519()
+                       if err != nil {
+                               return nil, nil, err
+                       }
+                       privData, err := priv.Bytes()
+                       if err != nil {
+                               return nil, nil, err
+                       }
+                       privKey := PrivateKey(privData)
+                       pubKey := privKey.Public().(PublicKey)
+                       return pubKey, privKey, err
+               }
+               boring.UnreachableExceptTests()
+       }
```

This means if nil is passed as rand to GenerateKey; rand will be initialised to crypto/rand.Reader, which is not crypto/internal/backend.RandReader, and codeblock will fail at crypto/internal/backend.UnreachabelExceptTests() by reaching it.

I don't see similar checks elsewhere. I also don't see The successful path using rand reader input at all. Maybe it shouldn't be checked at all, and unreachableexcepttests shouldn't be there either?

Or even move the `if boring.Enabled` block prior to the `if rand == nil` block?

**Comment by qmuntal** [comment]
`rand.Reader` is initialized as `boring.Reader` if `boring.Enabled` is true in here: https://github.com/golang/go/blob/2b33434287be85917ba8edc4a73f0a6ebaaea63e/src/crypto/rand/rand.go#L33. This means that if you pass a `nil` rand, then it will be assigned to `boring.Reader` and you won't hit the `UnreachableExceptTests`.

Are you reporting this issue for a specific failure on your end?

**Comment by xnox** [comment]
> Are you reporting this issue for a specific failure on your end?

I am trying to decipher incomplete traceback!

**Comment by xnox** [comment]
Looks like this is coming from here https://github.com/nats-io/nkeys/blob/c865baf4058b0ae6529eeb82fbe86bd8c21f4a36/keypair.go#L71

and here https://github.com/nats-io/nkeys/blob/c865baf4058b0ae6529eeb82fbe86bd8c21f4a36/keypair.go#L92

Note sure why it does such odd things.

**Comment by xnox** [comment]
Filed https://github.com/nats-io/nkeys/issues/67 requesting to improve their API usage.
