### ISSUE TITLE
Fill go-images platform and Go branch matrix, e.g. Buster with OpenSSL/FIPS Go toolset

### ISSUE THREAD

**Issue by dagood** [microsoft/go#418]
Right now, we basically have these Linux Dockerfiles:

* 1.17 bullseye
* 1.17 buster
* 1.17 stretch
* 1.17-fips cbl-mariner

The first three are inherited from https://github.com/docker-library/golang/tree/master/1.17. The last one is just us.

A fuller matrix would be:

* 1.17 bullseye
* 1.17 buster
* 1.17 stretch
* 1.17 cbl-mariner
* 1.17-fips bullseye
* 1.17-fips buster
* 1.17-fips stretch
* 1.17-fips cbl-mariner

An interesting scenario to consider: someone could want to build a FIPS-compatible Go application on Buster, then copy the application to run on Mariner to run with FIPS-compliant OpenSSL binaries. This would require the `1.17-fips buster` image.

Another scenario is someone who wants to use Mariner, but doesn't want the version of Go they use to include the FIPS/OpenSSL tooling in case it has bugs that aren't present in the "normal" Go build. This calls for the `1.17 cbl-mariner` image.

---

Should we add these images proactively?

* It's relatively easy to add a variant: add it to the list in `src/microsoft/versions.json` and regenerate the other files using `github.com/microsoft/go-infra/tree/main/cmd/dockerupdate`.
* A fuller matrix costs us in build time and ACR costs.

I think we can wait until someone asks for these variants. Or at least, until then, it's not a priority.

**Comment by qmuntal** [comment]
Adding `fips` to the image names might be misleading, at least it is to me. Does it mean it contains a Go toolchain that can produce FIPS-capable binaries? Does it also mean it contains a FIPS-capable OpenSSL that you can use with a FIPS-capable binary?

I'm against the latter unless the official base image already provides it, such as CBL-Mariner does. Installing the OpenSSL FIPS module in ubuntu is not trivial, and producing production-ready container images is not our business.

I agree with your conclusion, let's wait until someone asks for a container image that we do not already support so we can better understand the requirements.

**Comment by dagood** [comment]
Good point, we should rename the suffix to be more accurate. We should probably do this soon, to avoid migration issues if we rename it later. (If we wanted to have both `-fips` and `-something-more-specific`, I'm pretty sure we'd need to update the auto-update system to account for it. The tag is based on the `versions.json` entry, and we'd have to update two keys with the same build info.)

**Comment by dagood** [comment]
What came to mind first was `-os-crypto`. This avoids excluding Windows, for when we implement that. But, it excludes custom builds of FIPS-compliant OpenSSL that aren't in the base OS.

`-fips-builder`? At least that hints at the idea that you can build something that is FIPS-compliant, but it won't necessarily run that way on the image.

`-pluggable-crypto`? Throwing it out there. We've already plugged in OpenSSL and IIRC we aren't at the point where you can plug in completely new crypto implementations while building your own app. At least this doesn't set up any *dangerous* expectations.

**Comment by qmuntal** [comment]
Hmm, I don't really like these names, but I don't have anything better :P.

I know `-openssl` excludes Windows, but we are using cgo for the OpenSSL interop and you cannot cross compile when using cgo, so Windows (and other non-linux OS) are already excluded.

**Comment by qmuntal** [comment]
I amend the previous message. The toolchain uses Go crypto when cgo is disabled or OS is not linux, so one could use the FIPS-capable toolchain to build binaries in windows.

**Comment by dagood** [comment]
What I mean there is that in the future, we may have a Windows build of Go that uses Windows crypto to get FIPS compatibility. We'd probably want this Windows tag to share the suffix of the Linux tag, so someone can pull e.g. `.../oss/go/microsoft/golang/1.18-fips-builder` and automatically get something compatible with the host OS that does FIPSy builds.

**Comment by jaredpar** [comment]
The `-fips-builder` suffix feels good to me. Also was thinking of `-fips-toolset`

**Comment by dagood** [comment]
* Done by https://github.com/microsoft/go-images/pull/153.
* Filed https://github.com/microsoft/go/issues/695 to follow up on picking a better name.
