### ISSUE TITLE
Implement FIPS-compatible crypto for Windows using platform-native crypto library

### ISSUE THREAD

**Issue by dagood** [microsoft/go#476]
Use a native Windows crypto library (CNG) to implement Go's crypto library in the boring branches, so we can rely on the native library's FIPS compatibility.

This is the same approach we took on Linux, where we rely on OpenSSL crypto's FIPS compatibility.

Progress:

- [x] CI tests: https://github.com/microsoft/go-crypto-winnative/pull/2
- [x] rand: https://github.com/microsoft/go-crypto-winnative/pull/2
- [x] sha: 
  - [x] sha1: https://github.com/microsoft/go-crypto-winnative/pull/2
  - [ ] sha224: https://github.com/microsoft/go-crypto-winnative/issues/4
  - [x] sha256: https://github.com/microsoft/go-crypto-winnative/pull/2
  - [x] sha384: https://github.com/microsoft/go-crypto-winnative/pull/2
  - [x] sha512: https://github.com/microsoft/go-crypto-winnative/pull/2
- [x] hmac: https://github.com/microsoft/go-crypto-winnative/pull/3
- [x] rsa
  - [x] OAEP padding: https://github.com/microsoft/go-crypto-winnative/pull/6
  - [x] PKCS1 padding: https://github.com/microsoft/go-crypto-winnative/pull/6
  - [x] PSS padding: https://github.com/microsoft/go-crypto-winnative/pull/6
  - [x] No padding: https://github.com/microsoft/go-crypto-winnative/pull/6
- [x] ecdsa
- [x] aes
  - [x] ECB mode: https://github.com/microsoft/go-crypto-winnative/pull/5
  - [x] CBC mode: https://github.com/microsoft/go-crypto-winnative/pull/5
  - [x] GCM mode: https://github.com/microsoft/go-crypto-winnative/pull/5
  - [ ] CRT mode: https://github.com/microsoft/go-crypto-winnative/issues/4
- [ ] vendor into Go toolchain: https://github.com/microsoft/go/pull/645

**Comment by qmuntal** [comment]
Windows work is happening at https://github.com/microsoft/go-crypto-winnative

**Comment by jdrews** [comment]
Any update here? I'm very interested in this work! 

I tried following the link provided and it returns a 404. 
https://github.com/microsoft/go-crypto-winnative

**Comment by jaredpar** [comment]
> Any update here? 

The Windows support for FIPS is still under way. Had to pause it briefly to work on a different project but that has completed and we're back to getting our Windows FIPS implementation completed. 

> I'm very interested in this work!

Curious: where are you planning on using this? Trying to get a better sense of the people / projects that are taking a dependency on this work. 

> I tried following the link provided and it returns a 404.
https://github.com/microsoft/go-crypto-winnative

That should be `public` fairly soon.

**Comment by dagood** [comment]
> > https://github.com/microsoft/go-crypto-winnative
> 
> That should be `public` fairly soon.

The repo is now public. 🎉

**Comment by jdrews** [comment]
@jaredpar Sure! I have a few projects where I need to deploy FIPS enabled go microservices on Windows hosts at the edge of unreliable networks to comply with security requirements (FIPS 140-2). Currently I use BoringCrypto toolchains to compile the go microservices with FIPS and run them on Linux based virtual machines or docker containers. But being able to run these services native on the Windows hosts without requiring Linux virtual machines or docker containers would greatly reduce the compute usage and also simplify the deployment architecture.
