### ISSUE TITLE
Release: 1.19

### ISSUE THREAD

**Issue by ghost** [microsoft/go#680]
This issue tracks the status of the Microsoft build of Go 1.19.

I'm starting the release build now, and I'll post another comment when it succeeds or fails.

For more information about the microsoft/go release process, see [docs/release-process in microsoft/go-infra](https://github.com/microsoft/go-infra/tree/main/docs/release-process).

This comment was generated by: [1918939](https://dev.azure.com/dnceng/internal/_build/results?buildId=1918939)

**Comment by ghost** [comment]
[1918986](https://dev.azure.com/dnceng/internal/_build/results?buildId=1918986): :rotating_light: Failed to run microsoft/go build prep steps for 1.19.
[Click here to see 1918986 retry instructions.](https://dev.azure.com/dnceng/internal/_build/results?buildId=1918986&view=ms.vss-build-web.run-extensions-tab)

**Comment by ghost** [comment]
[1919142](https://dev.azure.com/dnceng/internal/_build/results?buildId=1919142): :rotating_light: Failed to run microsoft/go build prep steps for 1.19.
[Click here to see 1919142 retry instructions.](https://dev.azure.com/dnceng/internal/_build/results?buildId=1919142&view=ms.vss-build-web.run-extensions-tab)

**Comment by dagood** [comment]
Succeeded with the microsoft/go release tasks.

Job failure is because I closed the automatic 1.19 microsoft/go-images PR in favor of https://github.com/microsoft/go-images/pull/153 to add new 1.19-specific go-images changes.
