### ISSUE TITLE
Remind user to `cd` to the submodule directory when running `git go-patch rebase`

### ISSUE THREAD

**Issue by dagood** [microsoft/go#749]
If you're currently in the repo dir and run `git go-patch rebase`, it lets you start the rebase, but it might be very confusing that `git rebase ...` tells you there's no rebase in progress. `git-go-patch` knows the current directory and the submodule directory, so it could easily check if a `cd` is necessary and warn the user.

**Comment by qmuntal** [comment]
Been hit by this issue many times.
