### ISSUE TITLE
Remove the RSA key size checker in /crypto/tls/boring.go

### ISSUE THREAD

**Issue by zihanhan1203** [microsoft/go#774]
**Background**
This [line](https://github.com/golang/go/blob/2b0d842f4b24b3be4bcf02c7a796e3a4d3d952f6/src/crypto/tls/boring.go#L98) of code in /crypto/tls/boring.go limit the RSA key size to 2048 and 3072, which will cause an issue when we try to establish a TLS connection to the server with 4096 key size. There is an open issue to the official go https://github.com/golang/go/issues/41147 discussing about this. So we are seeking for a go version which replace the boring go with the openssl, and we found this repo.

**Issue**
However, we found that you didn't patch to the boring.go file I mentioned above, so we will still meet the same problem by using this go version.

**Request**
Is it possible you can add a patch to that boring.go file to remove or modify the RSA key size checker? It is safe to do it because we are now relying on the underlying openssl to be FIPS compliant, right?

**Comment by qmuntal** [comment]
Recent news: Upstream will probably land 4096 RSA key size support on go1.20: https://github.com/golang/go/issues/41147#issuecomment-1302422659.

**Comment by qmuntal** [comment]
Upstream implemented this and backported it to go1.18 and go1.19, so our fork will benefit from that too. We can close this.
