### ISSUE TITLE
Use MAR discovery portal rather than AZCU Indexer for MAR images

### ISSUE THREAD

**Issue by dagood** [microsoft/go#869]
MAR now allows auth-only access in the 2.1 version of the YAML: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/containers-bburns/microsoft-container-registry/microsoft-artifact-registry-also-known-as-microsoft-container-registry-docs/onboardingdocs/samples/yamltemplatediscoveryportal

Updating to 2.1 has other requirements, including making a readme in https://github.com/microsoft/mcrdocs to show on the portal.

See email thread "azcu indexer deprecation". We should try to get this done before April.

**Comment by jaredpar** [comment]
Once this is available we should update our internal landing page to point towards it. 

https://eng.ms/docs/more/languages-at-microsoft/go/articles/overview
