### ISSUE TITLE
React to `GOTOOLCHAIN=auto` default behavior

### ISSUE THREAD

**Issue by dagood** [microsoft/go#887]
* Re: https://github.com/golang/go/issues/57001

If someone installs our fork of Go, then tries to build a module with a newer e.g. go.mod `go 1.23` line, I expect that if we don't change anything, our Go binaries would grab upstream Go, build that, and start using it. This means no more FIPS (or any other patched features), which at best will be confusing.

The simple thing to do is patch the default to `local`. Or, to be safe, we could go one step further and make it always `local` for our fork.

We could look into supporting the `GOTOOLCHAIN=auto` and `GOTOOLCHAIN=1.2.3` behavior in a way that builds/installs a new version of our fork, not upstream Go. However: this fork is primarily focused on CI scenarios rather than dev scenarios, so I currently doubt there's enough value there for our users. It would be very important to do this correctly and get our implementation vetted etc. for security and supply chain reasons.

I expect our users also wouldn't be happy waiting to download and build Go for every single CI build, so they would not like the behavior if they saw it in their builds, anyway. One-time-use Docker containers with Go pre-installed is the general approach right now.

(I've let CBL-Mariner know about the proposal in their Teams channel for Packages. CBL-Mariner is one way that our build of Go is distributed, but CBL-Mariner also distributes ordinary upstream Go and may need to deal with this for that package too.)

**Comment by dagood** [comment]
* Completed by https://github.com/microsoft/go/pull/946

**Comment by zigo101** [comment]
It looks the name `local` will be replaced with `default`: https://go-review.googlesource.com/c/website/+/500775/1/_content/doc/toolchain.md

**Comment by zigo101** [comment]
Aha, I misread that draft article. It is still using "GOTOOLCHAIN=local" for go env.
