### ISSUE TITLE
Add compile-time flag that enables FIPS mode and ignores GOFIPS=0 at runtime

### ISSUE THREAD

**Issue by dagood** [microsoft/go#928]
A partner team has the responsibility to deliver FIPS-mode-only images containing a Go app to its customers. This could normally be done by setting GOFIPS=1 in the image's environment, but this image is meant to be used in a customer-defined AKS cluster, so the whole thing may be open to mistakes:

* The user could set `GOFIPS=0` to make some non-FIPS crypto algorithm work, perhaps not even aware they are working on a product that's meant to be FIPS-compliant.
* The user could clear out environment variables (perhaps attempting to have a "clean slate") causing `GOFIPS` to no longer be specified at all.

In these cases, instead of respecting the runtime `GOFIPS`, it would be better to fail. The images will have FIPS-specific tags, so the user is definitely interested in FIPS, and this is an opportunity to let the user know they made a configuration mistake.

We could add to goexperiment, so the app would be built with e.g. `GOEXPERIMENT=opensslcrypto,compelfips`.

---

This means the user can't toggle off FIPS mode to narrow down a runtime error. However, this technique is unlikely to be all that useful: they would still be using OpenSSL/CNG under the covers. It's also unlikely someone will try this: the images are more like appliances, so they will likely try to just swap out the tag to a non-FIPS tag--which would work fine.

**Comment by qmuntal** [comment]
I would go a little bit further. When someone builds an app using `GOEXPERIMENT=[opensslcrypto|cngcrypto]` the intent is clear, the app is meant to be FIPS-compliant, therefore `GOFIPS` should default to `1`. In other words, we should panic if a FIPS-compliant backend can't be loaded.

Your proposal is also good, but I expect `GOEXPERIMENT=opensslcrypto,compelfips` to be the default choice, so better make it simple and less verbose.

I'm not that sure about what to do with `GOFIPS`. We could remove it, but it's useful for development -having a FIPS-compliant OpenSSL is not that easy. If a production image sets `GOFIPS=0`, then that's a very explicit instruction, I would expect users to understand the consequences.

**Comment by dagood** [comment]
Interesting... here's kind of an inverse idea to add to consideration too:

* `GOEXPERIMENT=opensslcrypto` uses GOFIPS=1 behavior always
  * Maybe even ignoring env totally? Although I do think you have a good point that `GOFIPS=0` opt-out would be infeasible to stumble into accidentally.
* `GOEXPERIMENT=opensslcrypto,envfips` to use current GOFIPS env var + systemwide FIPS detection behavior.

**Comment by dagood** [comment]
Notes on naming from a sync: `requirefips` - Nice, describes what the program does at runtime. (Similar: `fipsrequired`)

It seems odd to call this a GOEXPERIMENT, `GOEXPERIMENT=systemcrypto go build -tags requirefips .` seems more like what we'd expect.

**Comment by dagood** [comment]
> `compelfips` to be the default choice

Another note from a sync: after some internal policy changes, using a backend *doesn't* mean the app will always be running on a FIPS-capable (or even FIPS-desired) system. We'll be keeping `requirefips` opt-in.
