### ISSUE TITLE
Add Docker images that specify `requirefips` with `GOFLAGS`

### ISSUE THREAD

**Issue by dagood** [microsoft/go#987]
* Pulled out of https://github.com/microsoft/go/issues/930
* Based on https://github.com/microsoft/go/issues/928

We could add tags like `golang:1.21-requirefips-bullseye` setting `GOFLAGS=-tags=requirefips`.

We only have one team who we know wants to use `requirefips`, and I'm not sure this image will be useful or potentially give a dangerous expectation for others who try to use it later. `-tags` specified in `GOFLAGS` are entirely dropped if `-tags=...` is present in the `go build` command, so putting it in the global environment of a `FROM` image seems risky if the build commands change without someone keeping a keen eye on this. And it might be difficult to keep an eye on it, because changes might come from upstream, or might be buried in a build script.

GOEXPERIMENT is a little more straightforward. You can remove an experiment by setting another (`GOEXPERMENT=somethingelse`), but that seems more obvious. It's easy to properly extend GOEXPERIMENT with `GOEXPERIMENT=$GOEXPERIMENT,foo`. I don't think it's as clear how to resolve a combination of `GOFLAGS` and `go build -tags=...`.

**Comment by qmuntal** [comment]
>We only have one team who we know wants to use requirefips, and I'm not sure this image will be useful or potentially give a dangerous expectation for others who try to use it later. 

I think that having a `requirefips` image will confuse users, as it wouldn't be straightforward to grasp the differences between `-fips` and `-requirefips`.

Right now it is a niche knob that we are even documenting not to use it the general case: https://github.com/microsoft/go/pull/970/files#diff-30de323f63b7da7bd97a87d8c834d4f0a834dd78c92bb3a8f9379c218e78a924R222. With this in mind, I would not add an image for it right now. Maybe in the future expectations and/or policies change and we can reconsider it.
